#!/bin/bash
exec >trafficgen-server-start-stderrout.txt
exec 2>&1

. /usr/bin/trafficgen-base || (echo "/usr/bin/trafficgen-base not found"; exit 1)

dump_runtime
validate_label

# Defaults
sample_dir=`/bin/pwd`
switch_type="testpmd"
num_devices=
devices=()
res_devs=()
res_devs_node=()
dev_count_node=()
node_cpus=()
dev_macs=()
total_devs=0
testpmd_forward_mode="mac"
testpmd_queues="1"
testpmd_queues_per_pmd="1"
testpmd_descriptors="2048"
testpmd_smt_mode="grouped"
testpmd_smt="on"
testpmd_mtu="1518"
testpmd_enable_scatter="off"
testpmd_enable_rx_cksum="off"
testpmd_enable_rss_udp="off"
testpmd_devopt=""
testpmd_mbuf_size=""
testpmd_burst=""
testpmd_dst_macs=""
testpmd_flow_control="off"
grout_forward_mode="ipv4"
grout_ip_addrs=""
grout_routes=""
grout_rxqs="1"
grout_qsize="2048"
grout_datapath_cpus=""
grout_control_cpus=""
grout_static_arp=""
grout_version=""

# Options processing
re='^(--[^=]+)=([^=]+)'
while [ $# -gt 0 ]; do
    if [[ "$1" =~ $re ]]; then
        arg="${BASH_REMATCH[1]}"
        val="${BASH_REMATCH[2]}"
        shift
    else
        arg="$1"
        shift
        val="$1"
        shift
    fi
    case "$arg" in
        --switch-type)
            switch_type="$val" # Can be "testpmd", "null", or "grout"
            ;;
        # The following two are needed to determine DPDK device IDs (0,1,2...)
        --server-devices)
            devices=(`echo "$val" | sed -e 's/,/ /g'`)
            num_devices=${#devices[@]}
            if [ $((num_devices%2)) -ne 0 ]; then
                exit_error "Number of devices ($num_devices) must be a multiple of 2, exiting" 1 "$sample_dir"
            fi
            ;;
        --testpmd-forward-mode)
            testpmd_forward_mode="$val"
            ;;
        --testpmd-queues)
            testpmd_queues="$val"
            ;;
        --testpmd-queues-per-pmd)
            testpmd_queues_per_pmd="$val"
            ;;
        --testpmd-descriptors)
            testpmd_descriptors="$val"
            ;;
        --testpmd-smt-mode)
            testpmd_smt_mode="$val"
            ;;
        --testpmd-smt)
            testpmd_smt="$val"
            ;;
        --testpmd-mtu)
            testpmd_mtu="$val"
            ;;
        --testpmd-devopt)
            testpmd_devopt="$val"
            ;;
        --testpmd-enable-scatter)
            testpmd_enable_scatter="$val"
            ;;
        --testpmd-enable-rx-cksum)
            testpmd_enable_rx_cksum="$val"
            ;;
        --testpmd-enable-rss-udp)
            testpmd_enable_rss_udp="$val"
            ;;
        --testpmd-mbuf-size)
            testpmd_mbuf_size="$val"
            ;;
        --testpmd-burst)
            testpmd_burst="$val"
            ;;
        --testpmd-dst-macs)
            testpmd_dst_macs="$val"
            ;;
	--testpmd-flow-control)
	    testpmd_flow_control="$val"
	    ;;
        --grout-forward-mode)
            grout_forward_mode="$val"
            ;;
        --grout-ip-addrs)
            grout_ip_addrs="$val"
            ;;
        --grout-routes)
            grout_routes="$val"
            ;;
        --grout-rxqs)
            grout_rxqs="$val"
            ;;
        --grout-qsize)
            grout_qsize="$val"
            ;;
        --grout-datapath-cpus)
            grout_datapath_cpus="$val"
            ;;
        --grout-control-cpus)
            grout_control_cpus="$val"
            ;;
        --grout-static-arp)
            grout_static_arp="$val"
            ;;
        --grout-version)
            grout_version="$val"
            ;;
    esac
done

if [ "$switch_type" == "testpmd" ]; then
    if [ -z "$devices" ]; then
        exit_error "Value for --server-devices was not found, exiting" 1 "$sample_dir"
    fi

    # trafficgen-server may receive a message about MACs from the traffic-generator
    echo "These files exist in ./msgs/rx:"
    /bin/ls -l msgs/rx
    file="msgs/rx/infra-start-end:1"
    if [ -e "$file" ]; then
        echo "Found $file:"
        cat $file
        testpmd_dst_macs=`jq -r '.macs[]' $file | tr "\n" "," | sed -e 's/,$//'`
    fi

    # Build testpmd cmdline opts for device selection
    echo "Resolving devices for testpmd based on devices [$devices]"
    testpmd_devices=""

    count=0
    for this_device in ${devices[@]}; do
        resolve_device this_res_dev $this_device
        res_devs[$count]=$this_res_dev
        this_node=$(cat "/sys/bus/pci/devices/${res_devs[$count]}/numa_node")
        if [ "$this_node" == "-1" ]; then
            echo "Reassigning NUMA node to 0 (from -1) for device $this_device"
            this_node=0
        fi
        res_devs_node[$count]=$this_node
        # Track total number of devices per node so CPUs can be allocated later
        if [ ! -n ${num_devs_node[$this_node]} ]; then
            num_devs_node[$this_node]=1
        else
            ((num_devs_node[this_node]++))
        fi
        testpmd_devices+=" --allow ${res_devs[$count]}"
        if [ -n "${testpmd_devopt}" ]; then
            testpmd_devices+=",${testpmd_devopt}"
        fi
        echo "Device $count: ${res_devs[$count]}, NUMA node: ${res_devs_node[$count]}"
        ((count++))
    done

    if [ -z "${testpmd_devices}" ]; then
        exit_error "Testpmd devices could not be found, exiting" 1 "$sample_dir"
    fi

    if [ -z "${HK_CPUS}" ] ; then
        exit_error "There are no housekeeping CPUs to use for testpmd" 1 "$sample_dir"
    else
        echo "HK_CPUS=${HK_CPUS}"
    fi

    # figure out the CPUs to use
    HK_CPUS_SEPARATED=$(echo "${HK_CPUS}" | sed -e "s/,/ /g")
    HK_CPUS_ARRAY=(${HK_CPUS_SEPARATED})
    if [ ${#HK_CPUS_ARRAY[@]} -lt 1 ]; then
        exit_error "You must have at least 1 HK_CPUS" 1 "$sample_dir"
    fi

    if [ -z "${WORKLOAD_CPUS}" ]; then
        exit_error "There are no dedicated/isolated CPUs to use for testpmd" 1 "$sample_dir"
    else
        echo "WORKLOAD_CPUS=${WORKLOAD_CPUS}"
    fi
    WORKLOAD_CPUS_SEPARATED=$(echo "${WORKLOAD_CPUS}" | sed -e "s/,/ /g")

    # Build a sequence of '--cpu' options for get-cpus-ordered.py that includes all of the workload cpus
    cpu_str=""
    for cpu in $WORKLOAD_CPUS_SEPARATED; do
        cpu_str+=" --cpu $cpu"
    done

    # Find the number of cpus needed per NUMA node, based on number of devices per node (and queues/pmd)
    #
    # First CPU is housekeeping for testpmd main thread
    testpmd_cpus="0@${HK_CPUS_ARRAY[0]},"
    cpu_idx=0
    for this_node in ${!num_devs_node[@]}; do
        echo "finding cpus for node [$this_node]"
        num_devs=${num_devs_node[$this_node]}
        ((total_devs+=num_devs))
        echo "num_devs: [$num_devs]"
        num_cpus=`echo "scale=0; $num_devs*$testpmd_queues/$testpmd_queues_per_pmd" | bc`
        # In case truncated to 0
        if [ $num_cpus -eq 0 ]; then
            num_cpus=1
        fi
        echo "num_cpus: [$num_cpus]"
        echo "$TOOLBOX_HOME/bin/get-cpus-ordered.py --smt $testpmd_smt --smt-enumeration $testpmd_smt_mode --numa-node $this_node $cpu_str"
        this_node_cpus=$($TOOLBOX_HOME/bin/get-cpus-ordered.py\
                                      --smt $testpmd_smt\
                                      --smt-enumeration $testpmd_smt_mode\
                                      --numa-node $this_node $cpu_str)
        echo "output:"
        echo "$this_node_cpus"
        this_node_cpus_trimmed=`echo -e "$this_node_cpus" | grep "final cpus:" | awk '{ print $3 }' | cut -d, -f-$num_cpus | sed -e "s/,/ /g"`
        echo "this_node_cpus_trimmed: [ $this_node_cpus_trimmed ]"
        for this_cpu in `echo $this_node_cpus_trimmed | sed -e 's/,/ /g'`; do
            ((cpu_idx++))
            testpmd_cpus+="$cpu_idx@$this_cpu,"
        done
    done
    testpmd_cpus=$(echo "$testpmd_cpus" | sed -e "s/,$//")


    # Detect what the testpmd numa memory configuration should be
    if pushd /sys/devices/system/node > /dev/null; then
        testpmd_mem=""

        for node in $(ls -1d node*); do
            NODE_NUM=$(echo ${node} | sed -e "s/node//")
            if echo " "${!num_devs_node[@]}" " | grep -q -P "\s$NODE_NUM\s"; then
                testpmd_mem+="1024,"
            else
                testpmd_mem+="0,"
            fi
        done

        testpmd_mem=$(echo "${testpmd_mem}" | sed -e "s/,$//")

        popd > /dev/null
    fi

    testpmd_cmdline_file="trafficgen-testpmd-cmdline-file.txt"
    testpmd_output="trafficgen-testpmd-stderrout.txt"
    testpmd_bin=$( command -v dpdk-testpmd || command -v testpmd )
    testpmd_opts=" --lcores ${testpmd_cpus}"
    testpmd_opts+=" --file-prefix ${cs_label}"
    testpmd_opts+=" --socket-mem ${testpmd_mem}"
    testpmd_opts+=" --huge-dir /dev/hugepages ${testpmd_devices}"
    testpmd_opts+=" -v" # shows the version on startup
    testpmd_opts+=" --"
    testpmd_opts+=" --cmdline-file ${testpmd_cmdline_file}"
    testpmd_opts+=" --nb-ports $total_devs"
    testpmd_opts+=" --nb-cores ${cpu_idx}"
    testpmd_opts+=" --auto-start"
    testpmd_opts+=" --stats-period=5"
    testpmd_opts+=" --rxq ${testpmd_queues}"
    testpmd_opts+=" --txq ${testpmd_queues}"
    testpmd_opts+=" --rxd ${testpmd_descriptors}"
    testpmd_opts+=" --txd ${testpmd_descriptors}"
    testpmd_opts+=" --max-pkt-len=${testpmd_mtu}"
    testpmd_opts+=" --record-core-cycles"
    testpmd_opts+=" --record-burst-stats"

    if [ "$testpmd_enable_scatter" == "on" ]; then
        testpmd_opts+=" --enable-scatter"
    elif [ "$testpmd_enable_scatter" == "off" ]; then
        echo "--enable-scatter will not be used"
    else
        exit_error "value for --testpmd-enable-scatter ($testpmd_enable_scatter) is not valid.  Use either 'on' or 'off'"
    fi

    if [ "$testpmd_enable_rx_cksum" == "on" ]; then
        testpmd_opts+=" --enable-rx-cksum"
    elif [ "$testpmd_enable_rx_cksum" == "off" ]; then
        echo "--enable-rx-cksum will not be used"
    else
        exit_error "value for --testpmd-enable-rx-cksum ($testpmd_enable_rx_cksum) is not valid.  Use either 'on' or 'off'"
    fi

    if [ "$testpmd_enable_rss_udp" == "on" ]; then
        testpmd_opts+=" --rss-udp"
    elif [ "$testpmd_enable_rss_udp" == "off" ]; then
        echo "--enable-rss-udp will not be used"
    else
        exit_error "value for --testpmd-enable-rss-udp ($testpmd_enable_rss_udp) is not valid.  Use either 'on' or 'off'"
    fi

    if [ ! -z "$testpmd_burst" ]; then
        testpmd_opts+=" --burst=$testpmd_burst"
    fi

    # Bump up the default mbuf if the MTU is large,
    # but allow a user-defined mbuf size to not be changed
    if [ "${testpmd_mtu}" -gt 2048 -a -z "$testpmd_mbuf_size" ]; then
        testpmd_mbuf_size=16384
        testpmd_opts+=" --mbuf-size=${testpmd_mbuf_size}"
    fi

    if [ ! -z "$testpmd_mbufs" ]; then
        testpmd_opts+=" --total-num-mbufs=${testpmd_mbufs}"
    fi

    if [ "$testpmd_forward_mode" == "mac" ]; then
        mac_file="msgs/rx/infra-start-end:1"
        if [ -z "$testpmd_dst_macs" ]; then
            exit_error  "[ERROR] Using forward-mode = mac, but did not get MAC addresses from TREX or --testpmd-dst-macs" 1 "$sample_dir"
        fi
        idx=0
        for this_mac in `echo $testpmd_dst_macs | sed -e 's/,/ /g'`; do
            testpmd_opts+=" --eth-peer $idx,$this_mac"
            ((idx++))
        done
        testpmd_opts+=" --forward-mode mac"
        if [ $idx -ne $total_devs ]; then
            exit_error "The number of destination macs did not match the number of devices for testpmd.  In order to use forward-mode=mac, the number of TRex devices and number of testpmd devices must match exactly." 1 $sample_dir
        fi
    else
        testpmd_opts+=" "
    fi

    # prepare the script that is passed to testpmd's --cmdline-file
    # parameter
    echo > ${testpmd_cmdline_file}

    case "${testpmd_flow_control}" in
	"on"|"off")
	    echo "Testpmd flow control will be set to: ${testpmd_flow_control}"
	    ;;
	*)
	    exit_error "value for --testpmd-flow-control (${testpmd_flow_contorl}) is not valid.  Use either 'on' or 'off'"
	    ;;
    esac
    for packet_action in "rx" "tx"; do
	for dev_idx in 0 1; do
	    echo "set flow_ctrl ${packet_action} ${testpmd_flow_control} ${dev_idx}" >> ${testpmd_cmdline_file}
	done
    done
    for dev_idx in 0 1; do
	echo "show port ${dev_idx} flow_ctrl" >> ${testpmd_cmdline_file}
    done

    echo "Contents of generated testpmd cmdline file: ${testpmd_cmdline_file}"
    echo "--- begin ---"
    cat ${testpmd_cmdline_file}
    echo "---- end ----"

    echo "Going to run: $testpmd_bin $testpmd_opts"
    ( ${testpmd_bin} ${testpmd_opts} 2>&1 & echo $! > trafficgen-server.pid ) | ${TOOLBOX_HOME}/bin/timestamper.py > ${testpmd_output} &
    sleep 5 # TODO: need a better wait
    if [ ! -e $testpmd_output ]; then
        exit_error "Could not find testpmd output file: [$testpmd_output]" 1 $sample_dir
    fi

    # Find the MACs for all devices, to be sent to TRex
    if [ "$testpmd_forward_mode" == "mac" ]; then
        sleep 10 # TODO: need a better wait
        if [ ! -e $testpmd_output ]; then
            exit_error "Could not find testpmd output file: [$testpmd_output]" 1 $sample_dir
        fi
        macs_json=""
        dev_idx=0
        while [ $dev_idx -lt $total_devs ]; do
            this_mac=`egrep "Port $dev_idx: [A-Fa-f0-9]{2}:[A-Fa-f0-9]{2}:[A-Fa-f0-9]{2}:[A-Fa-f0-9]{2}:[A-Fa-f0-9]{2}:[A-Fa-f0-9]{2}" $testpmd_output | awk -F"$dev_idx: " '{print $2}'`
            echo "MAC$dev_idx: $this_mac"
            if [ $dev_idx -gt 0 ]; then
                macs_json="${macs_json},"
            fi
            macs_json="${macs_json}\"${this_mac}\""
            dev_mac[$dev_idx]=$this_mac
            let dev_idx=$dev_idx+1
        done
        # Queue MAC info for the engine infrastructure to deliver
        echo '{"macs":['${macs_json}']}' >msgs/tx/svc
    fi
elif [ "$switch_type" == "grout" ]; then
    if [ -z "$devices" ]; then
        exit_error "Value for --server-devices was not found, exiting" 1 "$sample_dir"
    fi

    if [ -z "$grout_ip_addrs" ]; then
        exit_error "Value for --grout-ip-addrs is required when switch-type=grout" 1 "$sample_dir"
    fi

    grout_output="trafficgen-grout-stderrout.txt"
    grout_sock="/tmp/grout-bench-${cs_label}.sock"
    grout_init="/tmp/grout-bench-${cs_label}.init"

    echo "Resolving devices for grout based on devices [$devices]"
    count=0
    for this_device in ${devices[@]}; do
        resolve_device this_res_dev $this_device
        res_devs[$count]=$this_res_dev
        echo "Device $count: ${res_devs[$count]}"
        ((count++))
    done
    total_devs=$count

    echo "# Auto-generated by trafficgen-server-start" > ${grout_init}

    # Only set CPU affinity when explicitly requested via --grout-datapath-cpus.
    # The automatic fallback to HK_CPUS/WORKLOAD_CPUS is intentionally avoided because:
    # 1. It triggers a full datapath graph restart in Grout (all workers destroyed/recreated)
    # 2. Allocating all WORKLOAD_CPUS (often 20+) for just 2 RX queues is wasteful
    # 3. The graph restart can disrupt nexthop state and fast-path FIB synchronization
    # Grout's defaults (a few CPUs auto-detected) work well for functional validation.
    if [ -n "${grout_datapath_cpus}" ]; then
        ctrl_cpus="${grout_control_cpus:-0}"
        echo "affinity cpus set control ${ctrl_cpus} datapath ${grout_datapath_cpus}" \
            >> ${grout_init}
    fi

    grout_ip_array=($(echo "$grout_ip_addrs" | sed -e 's/,/ /g'))
    for ((i=0; i<total_devs; i++)); do
        echo "interface add port p${i} devargs ${res_devs[$i]} rxqs ${grout_rxqs} qsize ${grout_qsize}" \
            >> ${grout_init}
        if [ -n "${grout_ip_array[$i]}" ]; then
            echo "address add ${grout_ip_array[$i]} iface p${i}" >> ${grout_init}
        fi
    done

    if [ -n "${grout_routes}" ]; then
        for route in $(echo "$grout_routes" | sed -e 's/,/ /g'); do
            echo "route add ${route}" >> ${grout_init}
        done
    fi

    # Auto-generate or manually configure static ARP/nexthop entries.
    # Required for hardware PF ports (i40e/ice) where Grout's dynamic ARP
    # resolution may not work (see upstream Grout Issue #545).
    if [ -z "${grout_static_arp}" ]; then
        infra_file=$(ls msgs/rx/infra-start-end:* 2>/dev/null | head -1)
        if [ -n "$infra_file" -a -e "$infra_file" ]; then
            echo "Auto-generating nexthops from TRex infra message: $infra_file"
            cat "$infra_file"
            readarray -t trex_macs < <(jq -r '.macs[]' "$infra_file")
            readarray -t trex_ips < <(jq -r 'if .ips then .ips[] else empty end' "$infra_file" 2>/dev/null)

            for ((i=0; i<total_devs && i<${#trex_macs[@]}; i++)); do
                if [ -n "${trex_ips[$i]}" ]; then
                    peer_ip="${trex_ips[$i]}"
                else
                    subnet_ip=$(echo "${grout_ip_array[$i]}" | cut -d/ -f1)
                    peer_ip=$(echo "$subnet_ip" | sed 's/\.[0-9]*$/.100/')
                    echo "WARNING: No IP for TRex port $i in infra message, derived $peer_ip"
                fi
                echo "nexthop add l3 iface p${i} address ${peer_ip} mac ${trex_macs[$i]}" >> ${grout_init}
                # Add a gateway route so the entire subnet forwards via this
                # nexthop. Without this, only the exact peer_ip is covered by
                # the static entry; other IPs in the range (e.g. ASTF
                # client/server IP ranges) would fall back to dynamic ARP.
                subnet_base=$(echo "${grout_ip_array[$i]}" | cut -d/ -f1 | sed 's/\.[0-9]*$/.0/')
                subnet_mask=$(echo "${grout_ip_array[$i]}" | cut -d/ -f2)
                echo "route add ${subnet_base}/${subnet_mask} via ${peer_ip}" >> ${grout_init}
            done
            echo "Auto-generated ${#trex_macs[@]} nexthop and gateway route entries"
        else
            echo "WARNING: No infra message found. Grout will rely on dynamic ARP (may not work on i40e/ice)."
        fi
    else
        # Manual grout-static-arp from runfile (format: "iface/ip/mac;iface/ip/mac;...")
        for entry in $(echo "$grout_static_arp" | sed -e 's/;/ /g'); do
            arp_iface=$(echo "$entry" | cut -d/ -f1)
            arp_ip=$(echo "$entry" | cut -d/ -f2)
            arp_mac=$(echo "$entry" | cut -d/ -f3)
            echo "nexthop add l3 iface ${arp_iface} address ${arp_ip} mac ${arp_mac}" >> ${grout_init}
        done
    fi

    echo "Generated grout init file:"
    cat ${grout_init}

    if [ -n "${grout_version}" ]; then
        installed_ver=$(grout --version 2>/dev/null | grep -oP 'v[\d.]+' || echo "")
        if [ "${grout_version}" != "${installed_ver}" ]; then
            echo "Requested Grout ${grout_version}, installed: ${installed_ver:-none}. Updating..."
            install-grout.sh --version "${grout_version}" --insecure
            if [ $? -ne 0 ]; then
                exit_error "Failed to install Grout ${grout_version}" 1 "$sample_dir"
            fi
        else
            echo "Grout ${grout_version} already installed"
        fi
    fi

    grout_bin=$(command -v grout)
    if [ -z "${grout_bin}" ]; then
        exit_error "grout binary not found. Ensure server-workshop.json includes grout-install or specify --grout-version" 1 "$sample_dir"
    fi

    echo "Starting grout daemon: ${grout_bin} -s ${grout_sock}"
    ${grout_bin} -s ${grout_sock} > ${grout_output} 2>&1 &
    echo $! > trafficgen-server.pid

    grout_ready=0
    for attempt in $(seq 1 30); do
        if [ -S "${grout_sock}" ]; then
            grout_ready=1
            break
        fi
        sleep 1
    done
    if [ $grout_ready -eq 0 ]; then
        exit_error "Grout daemon failed to start within 30s. See ${grout_output}" 1 "$sample_dir"
    fi
    echo "Grout daemon ready after ${attempt}s"

    echo "Applying grout configuration"
    grcli -s ${grout_sock} -xef ${grout_init}
    if [ $? -ne 0 ]; then
        exit_error "Failed to apply grout configuration" 1 "$sample_dir"
    fi

    # Wait for all ports to reach 'running' state (link up)
    echo "Waiting for all Grout ports to reach link-up state..."
    link_wait=0
    link_max=30
    all_running=0
    while [ $all_running -eq 0 -a $link_wait -lt $link_max ]; do
        all_running=1
        for ((i=0; i<total_devs; i++)); do
            if ! grcli -s ${grout_sock} interface show 2>/dev/null | grep "p${i}" | grep -q "running"; then
                all_running=0
                break
            fi
        done
        if [ $all_running -eq 0 ]; then
            sleep 2
            ((link_wait+=2))
        fi
    done
    if [ $all_running -eq 1 ]; then
        echo "All Grout ports have link after ${link_wait}s"
    else
        echo "WARNING: Not all Grout ports have link after ${link_max}s (some may be disconnected)"
    fi

    echo "Grout interface status:"
    grcli -s ${grout_sock} interface show
    echo "Grout address status:"
    grcli -s ${grout_sock} address show
    echo "Grout route status:"
    grcli -s ${grout_sock} route show

    # Verify nexthop state - critical for fast-path forwarding.
    # Static nexthops with explicit MACs should show 'static' flag.
    # If nexthops are in 'new' state, fast-path won't use them and packets
    # will be rate-limited through the control plane (~3-5K pps).
    echo "Grout nexthop status:"
    grcli -s ${grout_sock} nexthop show

    # Allow Grout's datapath to fully synchronize nexthop entries into the
    # fast-path FIB. This is critical because:
    # 1. Grout Issue #545: ARP doesn't work on hardware PF ports (i40e/ice)
    # 2. Static nexthops need time to be installed in the rte_graph datapath
    # 3. Without this delay, packets hit the slow-path control plane
    echo "Waiting 5s for Grout datapath FIB synchronization..."
    sleep 5
    echo "Grout nexthop status after settle:"
    grcli -s ${grout_sock} nexthop show

    # Reset stats so counters only reflect actual test traffic,
    # not startup/ARP/FIB sync activity
    echo "Resetting Grout stats counters..."
    grcli -s ${grout_sock} stats reset

    # Launch periodic stats collector in the background
    collector_script="/usr/bin/grout-stats-collector.sh"
    if [ -x "${collector_script}" ]; then
        echo "Starting Grout stats collector (interval=5s)"
        ${collector_script} \
            --socket "${grout_sock}" \
            --interval 5 \
            --hw-output trafficgen-grout-hw-stats.csv \
            --sw-output trafficgen-grout-sw-stats.csv &
        echo $! > trafficgen-grout-collector.pid
        echo "Grout stats collector running (pid $(cat trafficgen-grout-collector.pid))"
    else
        echo "WARNING: ${collector_script} not found, skipping periodic stats collection"
    fi

    macs_json=""
    dev_idx=0
    while [ $dev_idx -lt $total_devs ]; do
        this_mac=$(grcli -s ${grout_sock} interface show \
            | awk -v port="p${dev_idx}" '$1 == port' \
            | grep -oE '([0-9a-fA-F]{2}:){5}[0-9a-fA-F]{2}')
        if [ -z "$this_mac" ]; then
            exit_error "Could not determine MAC for grout port p${dev_idx}" 1 "$sample_dir"
        fi
        echo "Grout p${dev_idx} MAC: ${this_mac}"
        if [ $dev_idx -gt 0 ]; then
            macs_json="${macs_json},"
        fi
        macs_json="${macs_json}\"${this_mac}\""
        let dev_idx=$dev_idx+1
    done
    echo '{"macs":['${macs_json}']}' >msgs/tx/svc

elif [ "$switch_type" == "null" ]; then
    echo "Using switch_type null, no setup required"
else
    exit_error "Invalid switch type used: $switch_type"
fi
