#!/bin/bash
# -*- mode: sh; indent-tabs-mode: nil; sh-basic-offset: 4 -*-
# vim: autoindent tabstop=4 shiftwidth=4 expandtab softtabstop=4 filetype=bash

SCRIPT_DIR=$(dirname $0)

traffic_profile=""
traffic_generator=""
dest_traffic_profile_path="trafficgen.profile"

while [ ! -z ${1} ]; do
    arg=$(echo ${1} | awk -F= '{ print $1 }')
    if [ "${arg}" == "--traffic-profile" ]; then
        traffic_profile=$(echo "${1}" | awk -F= '{ print $2 }')
        echo "Found traffic profile = ${traffic_profile}"
    elif [ "${arg}" == "--traffic-generator" ]; then
        traffic_generator=$(echo "${1}" | awk -F= '{ print $2 }')
        echo "Found traffic generator = ${traffic_generator}"
    else
        echo "Ignoring this argument: ${arg}"
    fi
    shift
done

if [ -z "${traffic_profile}" ]; then
    if [ "${traffic_generator}" == "trex-txrx-profile" ]; then
        echo "ERROR: You must supply --traffic-profile=<profile> when --traffic-generator=trex-txrx-profile"
        exit 3
    fi

    echo "No traffic profile to import detected"

    # create an empty traffic profile file to satisfy the rickshaw.json client file copy
    echo "unused/blank trafficgen profile" > ${dest_traffic_profile_path}

    exit 0
else
    if [ "${traffic_generator}" == "trex-txrx" ]; then
        echo "ERROR: You supplied a traffic profile (--traffic-profile=${traffic_profile}) while using --traffic-generator=trex-txrx.  This does not make sense."
        exit 4
    fi
fi

traffic_profile_path=""
if [ -n "${CRUCIBLE_HOSTFS_PWD}" ]; then
    echo "Using CRUCIBLE_HOSTFS_PWD=${CRUCIBLE_HOSTFS_PWD}"
    traffic_profile_path+="/hostfs/"
    traffic_profile_path+=${CRUCIBLE_HOSTFS_PWD}
    traffic_profile_path+="/"
fi
traffic_profile_path+=${traffic_profile}

if [ ! -e "${traffic_profile_path}" ]; then
    echo "ERROR: Could not find traffic profile [${traffic_profile_path}]"
    exit 1
else
    echo "Copying traffic profile ${traffic_profile_path} to ${dest_traffic_profile_path}"
    /bin/cp "${traffic_profile_path}" "${dest_traffic_profile_path}"

    echo "Contents of ${dest_traffic_profile_path}:"
    cat ${dest_traffic_profile_path}

    echo "Validating JSON traffic profile:"
    ${SCRIPT_DIR}/trafficgen/validate-traffic-profile.py --json ${dest_traffic_profile_path}
    RC=$?
    if [ ${RC} == 0 ]; then
        echo "JSON traffic profile passed validation"
        exit 0
    else
        echo "ERROR: JSON traffic profile failed validation"
        exit 2
    fi
fi
